#include "hook_signal.h"
#include "internal/types.h"
#include "internal/apth_event.h"
#include "internal/apth_signal.h"
#include "utils/lll.inline.h"

APTH_DEFINE_HOOK(sighandler_t, signal, (int sig, sighandler_t handler), (sig, handler))
{
    apth_hook_debug(signal);

    // Reject invalid signal number
    if (sig <= 0 || sig >= APTH_NSIG || sig == SIGKILL || sig == SIGSTOP)
        return apth_error(SIG_ERR, EINVAL);

    sighandler_t prev;

    lll_internal_lock(&APTH_GLOBAL_SIGACTIONS.lock);

    // Return old action
    prev = APTH_GLOBAL_SIGACTIONS.actions[sig].sa_handler;

    // Set new action
    APTH_GLOBAL_SIGACTIONS.actions[sig].sa_handler = handler;
    sigemptyset(&APTH_GLOBAL_SIGACTIONS.actions[sig].sa_mask);
    APTH_GLOBAL_SIGACTIONS.actions[sig].sa_flags = SA_RESTART;

    lll_internal_unlock(&APTH_GLOBAL_SIGACTIONS.lock);
    return prev;
}

APTH_DEFINE_HOOK(sighandler_t, __sysv_signal, (int sig, sighandler_t handler), (sig, handler))
{
    if (sig <= 0 || sig >= APTH_NSIG || sig == SIGKILL || sig == SIGSTOP)
        return apth_error(SIG_ERR, EINVAL);
    sighandler_t prev;
    lll_internal_lock(&APTH_GLOBAL_SIGACTIONS.lock);
    prev = APTH_GLOBAL_SIGACTIONS.actions[sig].sa_handler;
    APTH_GLOBAL_SIGACTIONS.actions[sig].sa_handler = handler;
    sigemptyset(&APTH_GLOBAL_SIGACTIONS.actions[sig].sa_mask);
    APTH_GLOBAL_SIGACTIONS.actions[sig].sa_flags = SA_RESTART;
    lll_internal_unlock(&APTH_GLOBAL_SIGACTIONS.lock);
    return prev;
}

APTH_DEFINE_HOOK(sighandler_t, sysv_signal, (int sig, sighandler_t handler), (sig, handler))
{
    return apth_func(__sysv_signal)(sig, handler);
}

// For signals like SIGKILL, SIGSTOP, SIGSEGV, SIGBUS, SIGFPE, SIGILL, etc,
// generated by hardware or could not be ignored, we must register the
// sigaction to kernel level (via `apth_func_raw(sigaction)`) as well, since
// they are generated by hardware and could not be simulated by software.
// For these signals, `libapth` will register a trampoline handler in kernel,
// and set the pending bit of the signal in triggering apth, and then return from
// then handler, instead of directly execute user registered handler in kernel
// context.
APTH_DEFINE_HOOK(int, sigaction,
                 (int sig, const struct sigaction *restrict act,
                  struct sigaction *restrict oldact),
                 (sig, act, oldact))
{
    apth_hook_debug(sigaction);

    // Reject invalid signal number
    if (sig <= 0 || sig >= APTH_NSIG || sig == SIGKILL || sig == SIGSTOP)
        return apth_error(-1, EINVAL);

    lll_internal_lock(&APTH_GLOBAL_SIGACTIONS.lock);

    // Return old action
    if (oldact != NULL)
        *oldact = APTH_GLOBAL_SIGACTIONS.actions[sig];

    // Set new action
    if (act != NULL)
        APTH_GLOBAL_SIGACTIONS.actions[sig] = *act;

    lll_internal_unlock(&APTH_GLOBAL_SIGACTIONS.lock);
    return 0;
}

// APTH variant of POSIX sigwait(3)
APTH_DEFINE_HOOK(int, sigwait, (const sigset_t *set, int *sigp), (set, sigp))
{
    apth_hook_debug(sigwait);

    apth_t self = CUR_APTH;
    if (set == NULL || sigp == NULL)
        return apth_error(EINVAL, EINVAL);

    // Check whether there's signal already pending
    lll_internal_lock(&self->siglock);
    for (int sig = 1; sig < APTH_NSIG; sig++)
    {
        if (sigismember(set, sig) && sigismember(&self->sigpending, sig))
        {
            sigdelset(&self->sigpending, sig);
            self->sigpendcnt--;
            lll_internal_unlock(&self->siglock);
            *sigp = sig;
            return 0;
        }
    }
    lll_internal_unlock(&self->siglock);

    // No signal is pending, then we should wait
    struct apth_event_st ev = EVENT_SIGS(set, sigp);
    apth_wait_event(&ev);
    assert(ev.ev_status != APTH_EV_STATUS_PENDING);
    return 0;
}

APTH_DEFINE_HOOK(int, raise, (int sig), (sig))
{
    apth_t self = CUR_APTH;
    if (APTH_IS_FAKE_SCHED(self))
        return apth_func_raw(raise)(sig);
    return apth_kill(self, sig);
}

APTH_DEFINE_HOOK(int, gsignal, (int sig), (sig))
{
    return apth_func(raise)(sig);
}

APTH_DEFINE_HOOK(int, sigprocmask,
                 (int how, const sigset_t *restrict set, sigset_t *restrict oldset),
                 (how, set, oldset))
{
    // Manual of sigprocmask(2) says:
    //   sigprocmask()  is used to fetch and/or change the signal mask of the calling thread.
    // The signal mask is the set of signals whose delivery is currently blocked for the
    // caller (see also signal(7) for more details).
    //
    // Manual also says:
    //   The use of sigprocmask() is unspecified in a multithreaded process;
    // see pthread_sigmask(3).
    //
    // Since `sigprocmask` behaviour is not specified, we could just redirect it to `apth_sigmask`
    return apth_sigmask(how, set, oldset);
}

APTH_DEFINE_HOOK(int, sigpending, (sigset_t * set), (set))
{
    if (set == NULL)
        return apth_error(-1, EFAULT);
    apth_t cur = CUR_APTH;
    if (APTH_IS_FAKE_SCHED(cur))
        return apth_func_raw(sigpending)(set);

    lll_internal_lock(&cur->siglock);
    *set = cur->sigpending;
    lll_internal_unlock(&cur->siglock);
    return 0;
}

// Event manager will check the signal
static bool __apth_sigsuspend_check(void *arg)
{
    apth_t th = (apth_t)arg;
    lll_internal_lock(&th->siglock);
    bool found = false;
    for (int sig = 1; sig < APTH_NSIG; sig++)
    {
        if (sigismember(&th->sigpending, sig) && !sigismember(&th->sigmask, sig))
        {
            found = true;
            break;
        }
    }
    lll_internal_unlock(&th->siglock);
    return found;
}

APTH_DEFINE_HOOK(int, pause, (void), ())
{
    apth_hook_debug(pause);

    // pause() suspends execution until any signal is caught
    // According to POSIX, pause() always returns -1 with errno set to EINTR
    // We implement this by waiting for any signal to be delivered

    apth_t self = CUR_APTH;

    // Check if there's already a pending unblocked signal
    lll_internal_lock(&self->siglock);
    for (int sig = 1; sig < APTH_NSIG; sig++)
    {
        if (sigismember(&self->sigpending, sig) && !sigismember(&self->sigmask, sig))
        {
            lll_internal_unlock(&self->siglock);
            // Deliver the signal and return
            apth_deliver_pending_signals(self);
            return apth_error(-1, EINTR);
        }
    }
    lll_internal_unlock(&self->siglock);

    // No signal pending, wait for any signal using a custom check function
    struct apth_event_st ev = EVENT_FUNC(__apth_sigsuspend_check,
                                         self, apth_time(0, 50000));
    apth_wait_event(&ev);

    // Deliver pending signal
    apth_deliver_pending_signals(self);

    return apth_error(-1, EINTR);
}

APTH_DEFINE_HOOK(int, sigsuspend, (const sigset_t *mask), (mask))
{
    apth_t self = CUR_APTH;

    // Replace signal mask temporarily
    sigset_t oldmask = self->sigmask;
    self->sigmask = *mask;

    // Wait for a non-blocked signal delivered
    struct apth_event_st ev = EVENT_FUNC(__apth_sigsuspend_check,
                                         self, apth_time(0, 50000));
    apth_wait_event(&ev);

    // Restore signal mask
    self->sigmask = oldmask;

    // Deliver pending signal to apth self
    apth_deliver_pending_signals(self);

    return apth_error(-1, EINTR);
}

APTH_DEFINE_HOOK(int, sigaltstack, (const stack_t *restrict ss, stack_t *restrict oss), (ss, oss))
{
    apth_t cur = CUR_APTH;
    if (oss != NULL)
    {
        if (cur->sigaltstack_set)
            *oss = cur->signalstack;
        else
        {
            oss->ss_sp = NULL;
            oss->ss_size = 0;
            oss->ss_flags = SS_DISABLE;
        }
    }
    if (ss != NULL)
    {
        if (ss->ss_flags & SS_DISABLE)
            cur->sigaltstack_set = false;
        else
        {
            cur->signalstack = *ss;
            cur->sigaltstack_set = true;
        }
    }
    return 0;
}

APTH_DEFINE_HOOK(int, sigstack,
                 (struct sigstack * stack, struct sigstack *oldstack),
                 (stack, oldstack))
{
    apth_hook_debug(sigstack);

    // sigstack() is obsolete and replaced by sigaltstack()
    // Convert between sigstack and stack_t structures
    stack_t ss, oss;

    if (stack != NULL)
    {
        ss.ss_sp = stack->ss_sp;
        ss.ss_size = SIGSTKSZ; // sigstack doesn't specify size, use default
        ss.ss_flags = stack->ss_onstack ? 0 : SS_DISABLE;
    }

    int result = apth_func(sigaltstack)(stack ? &ss : NULL, oldstack ? &oss : NULL);

    if (result == 0 && oldstack != NULL)
    {
        oldstack->ss_sp = oss.ss_sp;
        oldstack->ss_onstack = (oss.ss_flags & SS_ONSTACK) ? 1 : 0;
    }

    return result;
}